const lesson = (stage, detail) => ({stage, detail});

export const deepening = {
  'ai-map': {stages:[lesson('Frame the task','State the input, output, decision, and cost of failure.'),lesson('Choose a capability','Search, prediction, generation, perception, or control.'),lesson('Test the behavior','Use evidence that matches the intended use.'),lesson('Operate the system','Monitor exceptions, feedback, and changing conditions.')], decision:'The first design decision is not “which model?” It is whether the task needs a learned approximation at all. A rule, database query, calculator, optimizer, retrieval system, classifier, and generative model each fail in different ways. The most useful AI systems make those boundaries visible rather than pretending one component can do every job.', evidence:'Write an acceptance test before choosing a model. For each intended action, define the available evidence, an acceptable abstention path, the human or system allowed to act, and what counts as a harmful error.'},
  'bits-and-computers': {stages:[lesson('Encode','Represent a value as bits and a datatype.'),lesson('Move','Fetch it through storage, RAM, cache, and registers.'),lesson('Execute','Apply instructions using CPU or accelerator units.'),lesson('Persist','Write results with an explicit format and lifetime.')], decision:'Every apparent software abstraction eventually becomes a memory layout and a sequence of instructions. A model checkpoint is bytes on storage; loading it establishes tensors in memory; inference schedules arithmetic; a response becomes network bytes. This path explains why loading, serialization, and copying can be more important than FLOPS for small workloads.', evidence:'For any performance or capacity claim, name the representation, bytes per element, working-set size, storage location, and transfer path. Those five facts prevent most unit mistakes.'},
  'python-and-arrays': {stages:[lesson('Specify shapes','Name every axis and its semantic meaning.'),lesson('Transform','Use array operations with an explicit dtype.'),lesson('Validate','Assert shape, range, finiteness, and alignment.'),lesson('Measure','Benchmark representative sizes and allocations.')], decision:'Numerical programming is a discipline of contracts. A tensor shape is not decoration: it records which examples, positions, features, heads, or channels an operation is acting on. Most subtle errors occur when an operation is legal under broadcasting but semantically applies an axis in the wrong role.', evidence:'Keep a tiny hand-calculated input beside every new operation. Print shapes and a few values, then compare the vectorized result to a simple loop before scaling it.'},
  'algorithms-and-complexity': {stages:[lesson('Define input scale','Count records, edges, dimensions, and sequence length.'),lesson('Choose representation','Use an array, index, graph, cache, or stream.'),lesson('Find dependencies','Separate parallel work from reductions and sequential state.'),lesson('Measure reality','Include allocation, locality, I/O, and constants.')], decision:'Complexity is a way to eliminate impossible designs before implementation. It does not replace profiling. A quadratic algorithm can be ideal at small scale, and an asymptotically elegant method can lose because it creates scattered memory access or expensive setup. The right procedure is to estimate growth, then measure the actual operating range.', evidence:'Write one back-of-the-envelope calculation for every large intermediate. Count elements, bytes per element, and operations. If either number is outside the target machine’s capacity, change the algorithm before optimizing code.'},
  'systems-and-networking': {stages:[lesson('Receive','A request arrives with identity, deadline, and payload.'),lesson('Queue','Admission control decides whether work can begin.'),lesson('Execute','CPU, GPU, storage, and tools make progress asynchronously.'),lesson('Commit','Return or persist an idempotent, observable result.')], decision:'Distributed systems fail by being ambiguous. A timeout says the caller did not receive an answer; it does not say whether the server acted. A robust design therefore carries identity, deadlines, idempotency, cancellation, and durable state through the path rather than treating retries as harmless.', evidence:'Draw the request path and mark every boundary where work can be queued, retried, canceled, or committed. Then test each boundary with a forced delay and a repeated request.'},
  'linear-algebra': {stages:[lesson('Represent','Choose coordinates, shapes, and a basis.'),lesson('Transform','Apply a matrix as a linear map.'),lesson('Measure','Use dot products, norms, projections, and rank.'),lesson('Compress','Retain useful directions with low-rank structure.')], decision:'Linear algebra becomes useful when you read each symbol as a transformation of a space rather than a grid of arithmetic. A row of a weight matrix asks one learned question of an input; a column describes how one input coordinate contributes across outputs. Matrix multiplication composes these questions into layers.', evidence:'When reading an equation, annotate every object with its shape and ask what each axis means. If a multiplication has no interpretation in terms of mapping or aggregation, the notation has become disconnected from the model.'},
  'calculus-and-gradients': {stages:[lesson('Forward pass','Compute intermediate values and the loss.'),lesson('Local derivatives','Record how each operation changes nearby values.'),lesson('Backward pass','Apply the chain rule from loss to parameters.'),lesson('Update','Use the gradients with a controlled optimizer step.')], decision:'Backpropagation is an accounting method for responsibility. Each local derivative answers how an output would respond to a small input change; the chain rule sends that responsibility through the graph. It does not understand a task or select a learning rate. Those are modeling and optimization decisions made around it.', evidence:'For a new differentiable component, test the backward pass on a tiny input with finite differences. Compare directional derivatives rather than only individual elements when tensors are large.'},
  'probability-and-statistics': {stages:[lesson('Define event','State the population, outcome, and time horizon.'),lesson('Model uncertainty','Choose conditional variables and assumptions.'),lesson('Estimate','Use samples with known selection and dependence.'),lesson('Decide','Combine uncertainty with costs and thresholds.')], decision:'Probability is useful because it forces a conditional statement. “The model is 90% accurate” is incomplete without the population, label definition, base rate, threshold, and time period. A probability estimate supports a decision only if it is calibrated enough for the decision costs and remains valid after deployment shifts.', evidence:'For every rate, record both numerator and denominator. Then slice by the groups, time windows, and operating conditions that could change the denominator.'},
  'optimization': {stages:[lesson('State objective','Encode what improves and what constraints apply.'),lesson('Differentiate','Compute or estimate a direction of local change.'),lesson('Step','Apply a learning rate and optimizer state.'),lesson('Diagnose','Inspect loss, gradients, stability, and validation.')], decision:'An optimizer searches the objective you gave it, including accidental shortcuts in the data. Training curves are therefore evidence about the combined system of model, data, loss, numerical precision, and update rule. A stable decreasing training loss is necessary for many models but is not evidence of a useful deployed behavior.', evidence:'Change one optimization variable at a time. Save a baseline curve, gradient norms, and a validation metric. If an update diverges, find the first non-finite activation or gradient rather than treating NaN as a generic tuning issue.'},
  'information-theory': {stages:[lesson('Define distribution','Specify outcomes and conditioning context.'),lesson('Score predictions','Compare assigned probability with observations.'),lesson('Compress','Use predictable structure to reduce code length.'),lesson('Interpret','Separate likelihood from usefulness and truth.')], decision:'Information measures uncertainty under a distribution, not intelligence or factuality. Cross-entropy teaches a predictor to place probability mass on observed data. It does not directly optimize factual grounding, causal reasoning, safety, or a downstream task unless those are represented in data and the objective.', evidence:'When comparing language-model losses, lock the corpus, tokenizer, normalization, and evaluation procedure. A lower number across different token units is not a direct capability comparison.'},
  'data-lifecycle': {stages:[lesson('Collect','Record source, permissions, time, and unit of observation.'),lesson('Validate','Check schema, content, gaps, duplicates, and labels.'),lesson('Version','Freeze inputs, transformations, and split identity.'),lesson('Maintain','Track drift, corrections, access, and retirement.')], decision:'Data work is system design, not a preparatory chore. Labels reflect a process, sources change, and rows may represent related events rather than independent samples. A dataset that cannot explain where a record came from, when it was available, and how it was transformed cannot support a reliable model comparison.', evidence:'Treat a data contract like an API contract: validate it automatically and assign an owner. Store a small, reviewed fixture set of raw examples to catch semantic regressions that schema tests miss.'},
  'features-and-pipelines': {stages:[lesson('Split first','Create time-aware or group-aware evaluation partitions.'),lesson('Fit on train','Learn imputers, vocabularies, and scalers only there.'),lesson('Transform','Apply identical frozen logic to later data.'),lesson('Serve','Validate features and monitor changed distributions.')], decision:'Preprocessing is part of the model. A median imputer, category vocabulary, target encoder, and feature selector all encode information learned from data. Fitting them before a split lets validation influence training even if the final estimator never sees validation labels.', evidence:'Build one object that owns preprocessing and prediction. Test it on a record with reordered fields, unseen categories, missing values, and the units used by the real producer.'},
  'search-and-retrieval': {stages:[lesson('Ingest','Parse, normalize, version, and authorize documents.'),lesson('Index','Build lexical and vector representations.'),lesson('Retrieve','Generate a candidate set for the query.'),lesson('Verify','Rerank, cite, and abstain when evidence is absent.')], decision:'Retrieval quality places a hard ceiling on grounded generation. If the source passage is absent from the candidate set, a later reranker or language model cannot reliably recover it. Treat retrieval recall, source freshness, and authorization as first-class product metrics before prompt polish.', evidence:'Maintain a query set with required passages and unanswerable cases. Measure top-k evidence recall, citation entailment, latency, and access-control behavior separately.'},
  'supervised-learning': {stages:[lesson('Define target','Specify label time, decision, and error costs.'),lesson('Prepare split','Protect future, grouped, and held-out data.'),lesson('Fit baseline','Use a simple interpretable model first.'),lesson('Choose action','Calibrate and set a threshold for deployment.')], decision:'Supervised learning generalizes from a sample to a stated future population. The label is not the decision: a probability must still be converted into an action under asymmetric costs, capacity limits, and human review. Better classification ranking does not automatically improve intervention outcomes.', evidence:'Report a simple baseline, a held-out confusion matrix, calibration, and the operational threshold. Review examples around that threshold, because those are the cases the product will actually act on.'},
  'trees-and-ensembles': {stages:[lesson('Partition','A tree selects feature conditions.'),lesson('Regularize','Depth, leaves, and sampling control capacity.'),lesson('Combine','Average or sequentially correct weak learners.'),lesson('Inspect','Test importances and errors against leakage and proxies.')], decision:'Trees are powerful because they create interactions and nonlinear regions without feature engineering, but every split is a chance to memorize an accident of the sample. Forests reduce variance through diverse trees; boosting reduces residual error through sequential trees. The choice depends on data size, noise, latency, and explainability needs.', evidence:'Plot validation performance against depth or boosting rounds and use early stopping. Recompute feature attribution under perturbed data or alternate splits before treating it as an explanation.'},
  'unsupervised-learning': {stages:[lesson('Choose geometry','Decide distance, scaling, and neighborhood assumptions.'),lesson('Fit structure','Cluster, reduce dimensions, or score outliers.'),lesson('Stabilize','Repeat across seeds, samples, and settings.'),lesson('Interpret','Return to original variables and external evidence.')], decision:'Unsupervised methods discover structure relative to the representation you selected. K-means sees Euclidean compactness; PCA sees variance; density methods see local concentration. None discovers a natural category independent of measurement, scaling, and modeling assumptions.', evidence:'Treat every visualization as a hypothesis generator. Confirm it using raw examples, outcomes not used in fitting, and sensitivity checks across reasonable preprocessing choices.'},
  'evaluation-basics': {stages:[lesson('Specify outcome','Name the user decision and target population.'),lesson('Design split','Protect held-out data from all selection steps.'),lesson('Measure','Use metrics, uncertainty, and slices.'),lesson('Decide','Compare against baseline and operational constraints.')], decision:'Evaluation is an experiment design problem. The test set estimates behavior under the world your split represents. If deployment is temporal, grouped, adversarial, multilingual, or costly, a random aggregate score cannot answer the whole question. Measurement needs to follow the actual decision path.', evidence:'Create an evaluation card for every release: data version, split rule, sample size, baselines, metric definitions, confidence intervals, slices, latency, cost, and known blind spots.'},
  'neural-networks': {stages:[lesson('Encode','Map raw input to tensors and representations.'),lesson('Transform','Apply learned linear maps and nonlinearities.'),lesson('Score','Compare outputs with an objective.'),lesson('Learn','Backpropagate, update, validate, and repeat.')], decision:'A neural network is a compositional function with learned parameters, not a lookup table of answers. Its useful behavior depends on representation, architecture, objective, optimizer, and data together. More parameters increase capacity, but optimization, data coverage, and regularization determine whether that capacity becomes generalizable structure.', evidence:'Use the overfit-a-tiny-batch test as a first diagnostic. If a network cannot fit a handful of examples, investigate the data, loss, gradient path, and update loop before scaling the model.'},
  'convolution-and-sequences': {stages:[lesson('Choose inductive bias','Locality, recurrence, global attention, or state-space structure.'),lesson('Share computation','Reuse weights across positions or time.'),lesson('Build representation','Train with task labels or a self-supervised objective.'),lesson('Transfer','Adapt and evaluate under the target domain shift.')], decision:'Architectures encode assumptions about how information is organized. Convolution assumes nearby pixels share patterns; recurrence assumes a useful state can summarize the past; attention enables content-based interaction across positions. These are not interchangeable slogans: they change memory, parallelism, data needs, and failure modes.', evidence:'State which invariances your architecture should preserve and test them with controlled transformations. A representation that improves an average score can still break on the spatial, temporal, or domain shifts users care about.'},
  'accelerator-landscape': {stages:[lesson('Characterize workload','Measure shape, precision, batch, memory, and latency needs.'),lesson('Match hardware','Compare supported operations and memory model.'),lesson('Map software','Validate framework, compiler, kernels, and libraries.'),lesson('Benchmark system','Measure useful end-to-end throughput and tail latency.')], decision:'Accelerator choice is a workload and software decision. A theoretical peak describes a particular numerical operation under favorable conditions; it does not guarantee a specific model, framework, sequence length, or service will approach that peak. Memory capacity and a reliable kernel stack often matter more than the headline number.', evidence:'Benchmark the exact model configuration with warmup, representative prompts or batches, and the required quality setting. Compare cost and energy per accepted task, not only tokens or FLOPS.'},
  'reinforcement-learning': {stages:[lesson('Observe','Define state, partial observation, and reset conditions.'),lesson('Act','Select actions through a policy with exploration.'),lesson('Learn','Assign delayed reward through returns and value estimates.'),lesson('Evaluate','Test across seeds, scenarios, and real constraints.')], decision:'Reinforcement learning changes the data distribution as the policy changes it. This makes offline performance fragile: a model can prefer actions never well represented in its logged experience. Reward design is equally central, because the learner will exploit whatever proxy is easiest to optimize.', evidence:'Build a small environment with transparent rewards before adding a neural policy. Log trajectories, not only return, and inspect the policies that score best for unsafe or unintended strategies.'},
  'symbolic-ai': {stages:[lesson('Formalize','Define states, actions, constraints, and goals.'),lesson('Search or solve','Use an algorithm with understood guarantees.'),lesson('Check','Verify feasibility, cost, or proof obligations.'),lesson('Combine','Use learned models only at explicit interfaces.')], decision:'Symbolic methods shine when rules, constraints, and correctness conditions are explicit. A search algorithm can guarantee an optimal path under stated assumptions; a solver can prove a schedule feasible. Learned components can propose, rank, or parse, but the formal layer should verify the property it owns.', evidence:'For every planner, test invalid inputs, impossible goals, and changed transition rules. A correct solver result is only useful if the representation of the real-world constraints is itself correct.'},
  'prompting-and-context': {stages:[lesson('Specify task','State output contract, constraints, and success cases.'),lesson('Select context','Retrieve, order, and delimit relevant evidence.'),lesson('Generate','Constrain format and capture uncertainty.'),lesson('Validate','Check schema, sources, tools, and side effects.')], decision:'A prompt is an interface specification for a probabilistic component. It needs examples, boundary cases, versioning, and tests. Context selection is often the actual product intelligence: irrelevant or untrusted text can crowd out evidence and confuse instruction-following.', evidence:'Maintain a prompt test set with representative, ambiguous, adversarial, and unanswerable inputs. Validate structured output outside the model and log only the minimum data needed to diagnose failures.'},
  'audio-and-speech': {stages:[lesson('Capture','Sample sound with known devices, rate, and channels.'),lesson('Represent','Transform waveform into features or audio tokens.'),lesson('Model','Recognize, synthesize, separate, or classify sound.'),lesson('Experience','Stream with interruption, timing, and human listening tests.')], decision:'Audio systems live at the intersection of signal processing and interaction design. A transcript can be statistically strong yet fail on names, numbers, accents, or turn boundaries. A synthesized voice can be intelligible yet unnatural, too slow, or unsafe for the intended identity and consent context.', evidence:'Evaluate recordings from the real microphones, rooms, languages, and noise conditions. Measure first-audio latency and interruption handling alongside recognition or synthesis quality.'},
  'robotics-and-control': {stages:[lesson('Sense','Synchronize calibrated observations and state estimates.'),lesson('Plan','Choose a target or trajectory under constraints.'),lesson('Control','Close feedback loops within real-time deadlines.'),lesson('Recover','Detect uncertainty, stop safely, and replan.')], decision:'Robotics turns model error into physical consequences. A learned perception model may be one component of a safety-critical loop, but it cannot replace coordinate calibration, actuator limits, collision handling, control timing, and recovery. High-level reasoning and low-level control typically operate at very different rates.', evidence:'Test the complete loop under perturbations: latency, missing observations, lighting changes, object variation, contact, and emergency stop. Record near misses and interventions, not only successful completions.'},
  'mlops-and-deployment': {stages:[lesson('Package','Version model, data transforms, prompts, index, and runtime.'),lesson('Release','Shadow, canary, or gate a controlled cohort.'),lesson('Observe','Trace quality, latency, cost, drift, and failures.'),lesson('Recover','Roll back compatible artifacts and investigate.')], decision:'A deployment is a configuration of interacting artifacts, not a model file. Tokenizers, feature pipelines, vector indexes, prompts, model weights, tool permissions, and runtime versions can all change behavior. Treat the full configuration as a versioned release unit.', evidence:'Make rollback a rehearsed operation. Confirm that a candidate release can serve a real representative request through the same route, authorization, and monitoring path as a user.'},
  'cost-and-capacity': {stages:[lesson('Define demand','Specify arrival rate, concurrency, quality, and latency target.'),lesson('Model resources','Count memory, compute, links, storage, and queue capacity.'),lesson('Measure utilization','Observe saturation and tail latency under load.'),lesson('Choose policy','Set batching, limits, autoscaling, and fallback behavior.')], decision:'Capacity planning converts a vague performance goal into explicit tradeoffs. A service can increase total throughput by batching while making individual responses slower; a cheaper numerical format can reduce cost while changing quality; a larger memory pool can prevent failures while increasing idle spend.', evidence:'Run a load test with realistic prompt lengths and burst patterns. Report admission behavior, p50/p95/p99 latency, throughput, memory peak, error rate, and cost per accepted result.'},
  'security-and-privacy': {stages:[lesson('Identify trust','Mark untrusted text, identities, secrets, and tools.'),lesson('Constrain authority','Enforce scoped permissions outside the model.'),lesson('Validate actions','Check arguments, destinations, and high-impact requests.'),lesson('Respond','Log safely, detect abuse, revoke, and recover.')], decision:'The model is an interpreter of untrusted content, not a security boundary. Prompt injection, poisoned retrieval, and tool misuse are application trust problems. The strongest defense is limiting what any model output can do: scoped credentials, allowlisted operations, server-side authorization, and human approval for irreversible actions.', evidence:'Write threat cases that include malicious retrieved text and tool outputs. Verify actual authorization and side effects in traces, rather than only checking whether the assistant’s prose refused an instruction.'},
  'causality-and-fairness': {stages:[lesson('State intervention','Name the action and outcome, not only a prediction.'),lesson('Map assumptions','Represent possible confounders and selection paths.'),lesson('Estimate effect','Choose a design that identifies the question.'),lesson('Govern use','Set fairness objectives, recourse, and accountability.')], decision:'Causal and fairness questions require value judgments and assumptions that a predictive model cannot infer by itself. The right target is often an intervention effect, not a risk score. Fairness metrics can conflict because they encode different notions of equal treatment or error distribution.', evidence:'Document the decision process, affected groups, desired recourse, and uncertainty. Review data collection, labels, thresholding, and downstream policy together; changing only the model rarely resolves a systemic disparity.'},
  'history-and-evidence': {stages:[lesson('Name claim','State capability, reliability, cost, and deadline.'),lesson('Classify evidence','Separate demos, benchmarks, replication, and deployment.'),lesson('Find counterevidence','Look for scope, failures, and changing conditions.'),lesson('Update view','Record what would change the conclusion.')], decision:'AI history is full of genuine progress and overextended conclusions. A successful demonstration proves possibility under its setup; a benchmark measures a defined protocol; a reliable product must also handle exceptions, operations, incentives, and users. Treat each evidence type as answering a different question.', evidence:'Attach dates, versions, populations, baselines, and test conditions to claims. Preserve failed examples and disagreements alongside the headline result so the page stays useful after the news cycle changes.'},
  'capstone-projects': {stages:[lesson('Scope','Choose a bounded decision, data source, and acceptance criterion.'),lesson('Baseline','Build a simple reproducible end-to-end version.'),lesson('Evaluate','Measure quality, latency, cost, and failure cases.'),lesson('Deliver','Package artifacts, evidence, limitations, and next steps.')], decision:'A good capstone produces evidence, not just an interface. It should have an explicit baseline, a fixed evaluation set, run instructions, and a record of what failed. Choose a project small enough to finish the entire loop: collection, modeling, testing, deployment behavior, and a written assessment.', evidence:'Write the acceptance criteria before implementation. At the end, ask a peer to run the project from a clean environment and check whether the documented evidence supports the conclusion.'}
};

const esc = text => text.replace(/[&<>]/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]));
const lines = (text, size) => {
  const words = text.split(' '); const result = []; let line = '';
  for (const word of words) {
    if (`${line} ${word}`.trim().length > size && line) { result.push(line); line = word; } else line = `${line} ${word}`.trim();
  }
  if (line) result.push(line);
  return result.slice(0, 3);
};
const svgText = (items, x, y, className, step = 14) => `<text x="${x}" y="${y}" class="${className}">${items.map((line, index) => `<tspan x="${x}" dy="${index ? step : 0}">${esc(line)}</tspan>`).join('')}</text>`;

export function studyDiagram(title, stages) {
  const boxes = stages.map((item, i) => {
    const x = 28 + i * 171;
    return `<g><rect x="${x}" y="87" width="142" height="132" rx="8"/><text x="${x + 14}" y="116" class="step">0${i + 1}</text>${svgText(lines(item.stage, 18), x + 14, 141, 'diagram-title')}${svgText(lines(item.detail, 22), x + 14, 177, 'diagram-detail', 12)}${i < stages.length - 1 ? `<path class="connector" d="M${x + 143} 153H${x + 169}" marker-end="url(#arrow-${title.length})"/>` : ''}</g>`;
  }).join('');
  return `<div class="diagram authored-diagram"><svg viewBox="0 0 720 290" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="${esc(title)} workflow"><defs><marker id="arrow-${title.length}" markerWidth="8" markerHeight="8" refX="7" refY="3" orient="auto"><path d="M0,0 L7,3 L0,6 Z" fill="#7690b7"/></marker></defs><text x="28" y="39" class="diagram-overline">MENTAL MODEL</text><text x="28" y="64" class="diagram-heading">${esc(title)} — from question to evidence</text>${boxes}</svg><div class="diagram-caption">A usable chapter has a flow of decisions, evidence, and checks. Use this diagram as a navigation aid, then test each step on a small real example.</div></div>`;
}

export function deepenChapter(chapter) {
  const d = deepening[chapter.id];
  if (!d) return chapter;
  const workflow = `<h2>How the pieces connect</h2>${studyDiagram(chapter.title, d.stages)}`;
  const operating = `<h2>An operating model for ${chapter.title.toLowerCase()}</h2><p>${d.decision}</p><p>The diagram is deliberately sequential, but real systems loop. A surprising result may expose a bad representation; a production incident may reveal a missing evaluation slice; a performance limit may require an algorithmic change. The point is to preserve the link between the abstract concept, the evidence you observe, and the decision you make next.</p>`;
  const fieldGuide = `<h2>Field guide: four decisions in order</h2>${d.stages.map((item, index) => {
    const framing = [
      'Begin by making the object of study explicit. A vague input, target, or operating condition creates ambiguity that later computation cannot repair.',
      'Now make the mechanism inspectable. Prefer a small run whose intermediate values, examples, or traces can be examined before you automate a larger workflow.',
      'Treat the first result as a measurement, not a conclusion. Compare it with a baseline and vary one assumption at a time so that the observed change has an interpretable cause.',
      'Finish by connecting the result to a real choice. Record the operating range, uncertainty, and the condition under which the next person should stop, escalate, or revisit the earlier steps.'
    ][index];
    const practice = [
      'Write down the input boundary and the unit of analysis. This makes it possible to distinguish a missing fact from a mismatch between the question and the data or system.',
      'Keep a concrete artifact: a small dataset, a notebook cell, a trace, a benchmark command, or a hand-worked calculation. It is the fastest way to surface hidden assumptions.',
      'Check a deliberately awkward case alongside the happy path. Boundary conditions, rare examples, and resource limits reveal more than another aggregate score.',
      'Preserve the decision record with the result. A useful technical chapter leaves enough context for a reader to reproduce the reasoning, challenge it, and choose a safe next action.'
    ][index];
    return `<h3>${index + 1}. ${esc(item.stage)}</h3><p><strong>${esc(item.stage)} establishes the next constraint.</strong> ${esc(item.detail)} ${framing}</p><p>${practice}</p>`;
  }).join('')}`;
  const diagnosis = `<h2>When the first approach fails</h2><p>Do not respond to a weak result by immediately adding scale, complexity, or another framework. First locate the failure: the input may not match the intended problem; the representation may discard a useful signal; the measurement may reward the wrong outcome; or the system may have crossed a memory, latency, reliability, or authority boundary. Change one layer, repeat the smallest useful check, and keep the before-and-after evidence.</p><div class="callout warning"><strong>Gotcha.</strong> A polished output can hide an untested assumption. The most convincing demonstration is a counterexample the workflow handles deliberately, with the limitation stated in the release or research record.</div>`;
  const method = `<h2>A rigorous way to practice</h2><ol>${d.stages.map(item => `<li><strong>${esc(item.stage)}.</strong> ${esc(item.detail)}</li>`).join('')}</ol><p>${d.evidence}</p>`;
  const boundaries = `<h2>Questions that keep the chapter honest</h2><div class="table-scroll"><table><thead><tr><th>Ask</th><th>Why it matters</th><th>Evidence to collect</th></tr></thead><tbody><tr><td>What assumptions does this method make?</td><td>Every method encodes a view of data, hardware, or behavior.</td><td>Inputs, representations, constraints, and cases outside the expected range.</td></tr><tr><td>What would make the result fail?</td><td>Failure modes show where an aggregate result is fragile.</td><td>Boundary cases, counterexamples, slices, and perturbations.</td></tr><tr><td>What decision changes if it improves?</td><td>A metric only matters through an operational action.</td><td>Baseline, threshold, cost, latency, and human-review consequences.</td></tr></tbody></table></div>`;
  return {...chapter, html: chapter.html + workflow + operating + fieldGuide + diagnosis + method + boundaries};
}
