import {h,render,Fragment} from 'preact';
import {useState,useEffect,useRef} from 'preact/hooks';
import chapters from './manifest.json';
import {domains,paths} from './catalog.mjs';
import './style.css';
const byId=Object.fromEntries(chapters.map(t=>[t.id,t]));
const routes=()=>location.hash.slice(2).split('/').filter(Boolean);
const link=t=>t.id==='gpu'?'gpu.html':`#/read/${t.id}`;
const iconPaths={search:'m21 21-5-5 M18 10a8 8 0 1 1-16 0 8 8 0 0 1 16 0',arrow:'M5 12h14m-6-6 6 6-6 6',grid:'M3 3h7v7H3zM14 3h7v7h-7zM3 14h7v7H3zM14 14h7v7h-7z',book:'M12 5C8 2 3 3 3 3v16s5-1 9 2c4-3 9-2 9-2V3s-5-1-9 2zm0 0v16',terminal:'m5 7 5 5-5 5m8 0h6M2 3h20v18H2z',math:'M4 5h16M4 19h16M8 9l8 6m0-6-8 6',database:'M3 5c0-4 18-4 18 0s-18 4-18 0zm0 0v14c0 4 18 4 18 0V5M3 12c0 4 18 4 18 0',branches:'M12 3v6M5 15V9h14v6M2 15h6v6H2zM16 15h6v6h-6zM9 1h6v4H9z',network:'M5 5l14 7L5 19m0-14v14m14-7L5 12M3 3h4v4H3zM3 10h4v4H3zM3 17h4v4H3zM17 10h4v4h-4z',chip:'M6 6h12v12H6zM9 9h6v6H9zM9 2v4m6-4v4m-6 12v4m6-4v4M2 9h4m-4 6h4m12-6h4m-4 6h4',text:'M3 4h18M12 4v16M8 20h8M3 10h3m12 0h3',sliders:'M4 3v18M12 3v18M20 3v18M1 8h6m2 8h6m2-9h6',route:'M5 3v13a4 4 0 0 0 8 0V8a4 4 0 0 1 8 0v13M2 6l3-3 3 3m10 12 3 3 3-3',scan:'M3 8V3h5m8 0h5v5m0 8v5h-5m-8 0H3v-5M7 12l3 3 7-7',server:'M3 3h18v7H3zM3 14h18v7H3zM6 6h1m-1 11h1m4-11h7m-7 11h7',shield:'m12 2 9 4v6c0 6-9 10-9 10S3 18 3 12V6zm-5 10 3 3 7-7',bookmark:'M5 3h14v19l-7-5-7 5z',check:'m4 12 5 5L20 6',menu:'M3 6h18M3 12h18M3 18h18',close:'m5 5 14 14M5 19 19 5',flask:'M9 2h6m-5 0v7L3 21h18L14 9V2M7 15h10',clock:'M12 7v5l3 2M22 12a10 10 0 1 1-20 0 10 10 0 0 1 20 0',external:'M14 3h7v7m0-7L10 14M10 3H3v18h18v-7'};
function Icon({name='book',size=20,...props}){return <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true" {...props}><path d={iconPaths[name]||iconPaths.book}/></svg>}
function useSaved(key){const [value,setValue]=useState(()=>{try{const v=JSON.parse(localStorage.getItem(key)||'[]');return Array.isArray(v)?v:[]}catch{return []}});function set(v){setValue(v);try{localStorage.setItem(key,JSON.stringify(v))}catch{}}return [value,set]}
function App(){
 const [route,setRoute]=useState(routes),[menu,setMenu]=useState(false),[search,setSearch]=useState(false),[saved,setSaved]=useSaved('aie-bookmarks-v1'),[done,setDone]=useSaved('aie-complete-v1');
 const [section,id]=route;const topic=byId[id];
 useEffect(()=>{const change=()=>{setRoute(routes());setMenu(false);window.scrollTo(0,0)};addEventListener('hashchange',change);const key=e=>{if((e.metaKey||e.ctrlKey)&&e.key==='k'){e.preventDefault();setSearch(v=>!v)}};addEventListener('keydown',key);return()=>{removeEventListener('hashchange',change);removeEventListener('keydown',key)}},[]);
 useEffect(()=>{document.title=(topic?.title||({paths:'Learning paths',labs:'Interactive labs',sources:'Evidence index',saved:'Saved chapters',library:'All chapters'}[section])||'The AI knowledge library')+' — Axiom'},[section,id]);
 const toggle=(arr,set,k)=>set(arr.includes(k)?arr.filter(x=>x!==k):[...arr,k]);
 return <><a class="skip" href="#main-content" onClick={e=>{e.preventDefault();document.getElementById('main-content')?.focus()}}>Skip to content</a>
 <header class="masthead"><button class="icon-button mobile-toggle" aria-label="Toggle navigation" aria-expanded={menu} onClick={()=>setMenu(!menu)}><Icon name="menu"/></button><a class="brand" href="#/"><span class="brand-mark">A<span>•</span></span><span>Axiom<span class="brand-label">THE AI FIELD LIBRARY</span></span></a><div class="top-links"><a href="#/library">Explore</a><a href="#/paths">Learning paths</a><a href="perspective.html">Perspective</a><a href="#/labs">Labs <span class="tiny-new">4</span></a></div><button class="search-trigger" onClick={()=>setSearch(true)}><Icon name="search" size={17}/><span>Search everything</span><kbd>⌘ K</kbd></button><a class="top-saved icon-button" href="#/saved" aria-label="Saved chapters"><Icon name="bookmark"/></a></header>
 {menu&&<button class="nav-backdrop" aria-label="Close navigation" onClick={()=>setMenu(false)}/>}
 <aside class={`sidebar ${menu?'open':''}`}><div class="nav-overview"><a class={!section?'selected':''} href="#/"><Icon name="grid"/>Overview</a><a class={section==='library'?'selected':''} href="#/library"><Icon name="book"/>All chapters <span>{chapters.length}</span></a><a class={section==='paths'?'selected':''} href="#/paths"><Icon name="route"/>Learning paths</a><a href="perspective.html"><Icon name="scan"/>Perspective & society</a><a class={section==='labs'?'selected':''} href="#/labs"><Icon name="flask"/>Interactive labs</a></div><div class="side-label">THE FIELD LIBRARY</div><nav aria-label="Library hierarchy">{domains.map((d,i)=>{const domainChapters=chapters.filter(t=>t.group===d.id);const isOpen=topic?.group===d.id||(section==='domain'&&id===d.id);return <div class={`nav-domain ${isOpen?'expanded':''}`}><a href={`#/domain/${d.id}`} class={isOpen?'selected':''}><span class="nav-number">{String(i+1).padStart(2,'0')}</span>{d.short}<span class="domain-count">{domainChapters.length}</span></a>{isOpen&&<div class="nav-children">{domainChapters.map(ch=>{const isCurrent=topic?.id===ch.id;return <div class="nav-chapter-wrap"><a class={`nav-chapter ${isCurrent?'current':''}`} href={link(ch)}><span class="nav-chapter-number">{String(ch.number).padStart(2,'0')}</span><span>{ch.title}</span></a>{isCurrent&&<div class="nav-sections">{ch.headings.map((heading,index)=><a href={`#/read/${ch.id}`} onClick={e=>{e.preventDefault();document.getElementById(heading.id)?.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth',block:'start'})}}><span>{String(index+1).padStart(2,'0')}</span>{heading.title}</a>)}</div>}</div>})}</div>}</div>})}</nav><div class="nav-bottom"><a href="#/sources"><Icon name="book" size={16}/>Evidence index</a><a href="#/saved"><Icon name="bookmark" size={16}/>Saved chapters<span>{saved.length}</span></a><div class="side-progress"><div><span>Your learning</span><b>{done.length}/{chapters.length}</b></div><progress max={chapters.length} value={done.length}/><small>Progress saved on this device</small></div></div></aside>
 <main id="main-content" class={`workspace ${section==='read'?'reading-workspace':''}`} tabIndex="-1">
 {section==='read'?(topic?<Reader key={id} topic={topic} saved={saved.includes(id)} done={done.includes(id)} onSave={()=>toggle(saved,setSaved,id)} onDone={()=>toggle(done,setDone,id)}/>:<Empty title="Chapter not found" text="Explore the library to find a chapter."/>):section==='paths'?<Paths done={done}/>:section==='labs'?<Labs/>:section==='sources'?<Sources/>:section==='saved'?<><PageHead eyebrow="YOUR LIBRARY" title="Saved for later." text="Keep useful references within reach. Bookmarks stay on this device."/><TopicList items={chapters.filter(t=>saved.includes(t.id))} done={done}/>{!saved.length&&<Empty title="Your reading list starts here" text="Open a chapter and use Save chapter to add it to this list."/>}</>:section==='domain'?<Domain id={id} done={done}/>:section==='library'?<Library done={done}/>:<Home done={done}/>}</main>
 {search&&<Search onClose={()=>setSearch(false)}/>}
 </>
}
function PageHead({eyebrow,title,text}){return <header class="page-head"><div class="eyebrow">{eyebrow}</div><h1>{title}</h1><p>{text}</p></header>}
function Home({done}){
 return <><div class="page-breadcrumb">AXIOM <span>/</span> THE COMPLETE FIELD LIBRARY <span class="edition">FOUNDATIONS · FRONTIER · SOCIETY</span></div><section class="home-hero"><div><div class="eyebrow"><span class="blue-square"/> A FIELD GUIDE TO ARTIFICIAL INTELLIGENCE</div><h1>Learn the machinery.<br/><span>Question the consequences.</span></h1><p>A connected library for the mathematics, hardware, models, products, institutions, and contested choices shaping AI. Start with a system, then follow the evidence around it.</p><div class="hero-actions"><a class="primary-link" href="#/read/ai-map">Start with the foundations <Icon name="arrow" size={17}/></a><a class="text-link" href="perspective.html">Read the Perspective volume <span>↗</span></a></div><div class="hero-facts"><span><b>13</b> disciplines</span><span><b>{chapters.length}</b> chapters</span><span><b>1</b> editorial fieldbook</span></div></div><KnowledgeGraphic/></section>
 <div class="orientation-strip"><span class="strip-index">00 → 100</span><p><strong>New to AI?</strong> Start with computers and math. Already building? Go straight to architectures, tools, or the GPU handbook.</p><a href="#/paths" aria-label="Choose a learning path"><Icon name="arrow"/></a></div>
 <section class="featured"><a class="gpu-feature" href="gpu.html"><div class="feature-copy"><div class="eyebrow">HARDWARE / VISUAL HANDBOOK</div><h2>Inside the GPU.</h2><p>From a single thread to a cluster: diagrams, code, memory arithmetic, and the physical machine behind modern AI.</p><span class="feature-meta">24 sections <span>·</span> diagrams & code <span class="round-arrow">↗</span></span></div><div class="chip-art" aria-hidden="true"><div class="chip-pins"><div class="chip-core"><span>GPU</span><small>PARALLEL COMPUTE</small><div class="mini-matrix">{Array.from({length:24},(_,i)=><i style={{opacity:i%5===0?.3:1}}/>)}</div></div></div></div></a><a class="perspective-feature" href="perspective.html"><div class="eyebrow">PERSPECTIVE / THE REVOLUTION HANDBOOK</div><h2>Who decides what AI becomes?</h2><p>People, power, energy, contested forecasts, and the evidence that should change your mind.</p><span>18 dossiers · 6 fault lines · 10 critical tools <Icon name="arrow" size={18}/></span></a></section>
 <div class="section-heading"><div><div class="eyebrow">THE COMPLETE MAP</div><h2>Choose a discipline.</h2></div><a class="text-link" href="#/library">Browse all {chapters.length} chapters <Icon name="arrow" size={17}/></a></div><div class="domain-grid">{domains.map((d,i)=>{const ts=chapters.filter(t=>t.group===d.id);return <a class="domain-card" href={`#/domain/${d.id}`} style={{'--domain':d.color}}><div class="domain-card-top"><span class="domain-icon"><Icon name={d.icon} size={23}/></span><span class="eyebrow">{String(i+1).padStart(2,'0')} / {ts.length} CHAPTERS</span><Icon name="arrow" size={18}/></div><h3>{d.name}</h3><p>{d.description}</p><div class="domain-topics">{ts.slice(0,3).map(t=><span>{t.title.split(':')[0].split(' & ')[0]}</span>)}{ts.length>3&&<span>+{ts.length-3} more</span>}</div></a>})}</div><Footer/></>
}
function KnowledgeGraphic(){return <div class="knowledge-graphic" aria-label="AI knowledge stack: computing and mathematics support learning, models, and real-world systems"><div class="graphic-top"><span>THE AI KNOWLEDGE STACK</span><span>FIG. 01</span></div><div class="stack-level top"><span class="stack-node"><Icon name="route" size={18}/></span><b>Real-world systems</b><small>Agents · Products · Robotics</small></div><div class="stack-connect">↑<span>put intelligence to work</span></div><div class="stack-level models"><span class="stack-node"><Icon name="network" size={18}/></span><b>Models & architectures</b><small>Language · Vision · Audio</small></div><div class="stack-connect">↑<span>learn useful representations</span></div><div class="stack-level learning"><span class="stack-node"><Icon name="sliders" size={18}/></span><b>Learning & optimization</b><small>Data · Objectives · Evaluation</small></div><div class="stack-connect">↑<span>build on the fundamentals</span></div><div class="stack-base"><span><Icon name="terminal" size={18}/> Computing</span><span><Icon name="math" size={18}/> Mathematics</span></div><div class="graphic-caption"><i/> Everything connects. Start at any layer.</div></div>}
function TopicList({items,done=[]}){return <div class="topic-list">{items.map(t=><a class="topic-row" href={link(t)}><span class={`topic-number ${done.includes(t.id)?'is-done':''}`}>{done.includes(t.id)?<Icon name="check" size={17}/>:t.number}</span><div><h3>{t.title}{t.id==='gpu'&&<span class="inline-badge">VISUAL HANDBOOK</span>}</h3><p>{t.summary}</p></div><span class="topic-level">{t.level}</span><span class="topic-time">{t.minutes} min</span><Icon name="arrow" size={18}/></a>)}</div>}
function Domain({id,done}){const d=domains.find(x=>x.id===id);if(!d)return <Empty title="Discipline not found" text="Choose a discipline from the library."/>;return <><a class="back-link" href="#/">← All disciplines</a><PageHead eyebrow={`DISCIPLINE ${String(domains.indexOf(d)+1).padStart(2,'0')} / ${chapters.filter(t=>t.group===id).length} CHAPTERS`} title={d.name} text={d.description}/><TopicList items={chapters.filter(t=>t.group===id)} done={done}/><Footer/></>}
function Library({done}){const [filter,setFilter]=useState('All levels');return <><PageHead eyebrow="THE FULL REFERENCE" title="The whole picture." text="Every chapter, organized by discipline. Follow the sequence or jump to the problem you’re working on."/><div class="filter-bar">{['All levels','Foundation','Intermediate','Advanced'].map(x=><button class={filter===x?'active':''} onClick={()=>setFilter(x)}>{x}</button>)}</div>{domains.map(d=>{const ts=chapters.filter(t=>t.group===d.id&&(filter==='All levels'||t.level===filter));return ts.length>0&&<section class="library-group"><h2><Icon name={d.icon}/>{d.name}<span>{ts.length}</span></h2><TopicList items={ts} done={done}/></section>})}<Footer/></>}
function Paths({done}){return <><PageHead eyebrow="CURATED LEARNING PATHS" title="A starting point. A clear direction." text="Four routes through the same connected library. Each path puts prerequisites before the ideas that depend on them."/><div class="paths-grid">{paths.map((path,i)=><section class="path-card"><div class="eyebrow">0{i+1} / {path.tag}</div><h2>{path.title}</h2><p>{path.description}</p><div class="path-progress"><span>{path.ids.filter(x=>done.includes(x)).length} of {path.ids.length} chapters completed</span><progress max={path.ids.length} value={path.ids.filter(x=>done.includes(x)).length}/></div><ol>{path.ids.map(id=><li class={done.includes(id)?'completed':''}><a href={link(byId[id])}>{byId[id].title}<Icon name={done.includes(id)?'check':'arrow'} size={15}/></a></li>)}</ol></section>)}</div><Footer/></>}
function Reader({topic,saved,done,onSave,onDone}){
 const [article,setArticle]=useState(null),[error,setError]=useState(false),[progress,setProgress]=useState(0);const bodyRef=useRef();
 useEffect(()=>{const c=new AbortController();fetch(`./content/${topic.id}.json`,{signal:c.signal}).then(r=>{if(!r.ok)throw Error(r.status);return r.json()}).then(setArticle).catch(e=>{if(e.name!=='AbortError')setError(true)});return()=>c.abort()},[topic.id]);
 useEffect(()=>{if(!article)return;const root=bodyRef.current;root.querySelectorAll('svg').forEach((s,i)=>{s.setAttribute('role','img');s.setAttribute('aria-label',s.closest('.diagram')?.querySelector('.diagram-caption')?.textContent||`Technical diagram ${i+1}`)});const scroll=()=>{const b=root.getBoundingClientRect();setProgress(Math.max(0,Math.min(100,(160-b.top)/Math.max(1,b.height-innerHeight+160)*100)))};scroll();addEventListener('scroll',scroll,{passive:true});return()=>removeEventListener('scroll',scroll)},[article]);
 const domain=domains.find(x=>x.id===topic.group);const pos=chapters.findIndex(t=>t.id===topic.id);const next=chapters[pos+1];
 return <><div class="reader-progress" style={{width:progress+'%'}}/><div class="reader-breadcrumb"><a href="#/">Library</a><span>/</span><a href={`#/domain/${domain.id}`}>{domain.short}</a><span>/</span><span>Chapter {topic.number}</span></div><div class="reader-layout"><div class="reading-column"><header class="article-head"><div class="eyebrow">{domain.name.toUpperCase()} / {topic.level.toUpperCase()}</div><h1>{topic.title}</h1><p>{topic.summary}</p><div class="article-meta"><span><Icon name="clock" size={15}/>{topic.minutes} min read</span><span>{topic.headings.length} sections</span><button onClick={onSave} class={saved?'saved':''}><Icon name={saved?'check':'bookmark'} size={15}/>{saved?'Saved':'Save chapter'}</button></div></header>{topic.prerequisites.length>0&&<div class="prerequisites"><span>BEFORE YOU BEGIN</span><div>{topic.prerequisites.map(id=><a href={link(byId[id])}>{byId[id].title}<span>↗</span></a>)}</div></div>}
 {error?<div role="alert" class="empty-state"><h2>This chapter could not be loaded.</h2><p>Check the local server connection, then reload the page.</p><button class="primary-link" onClick={()=>location.reload()}>Reload</button></div>:!article?<p role="status">Loading chapter…</p>:<><article ref={bodyRef} class="prose" dangerouslySetInnerHTML={{__html:article.html}}/><section class="article-sources"><div class="eyebrow">EVIDENCE USED IN THIS CHAPTER</div><p class="source-note">Source names are retained as an internal evidence ledger so the library stays a self-contained reading experience.</p>{topic.sources.map(([name])=><div class="source-entry"><Icon name="book" size={15}/>{name}</div>)}{topic.origin==='Frontier reference'&&<p class="source-note">This chapter preserves and extends the existing Frontier reference. Product comparisons and fast-moving claims are presented as dated context rather than a live recommendation feed.</p>}</section><div class="complete-box"><div><h3>{done?'Chapter completed.':'Make it part of what you know.'}</h3><p>Mark this chapter complete to track your learning.</p></div><button class={done?'secondary-button':'primary-link'} onClick={onDone}><Icon name="check" size={17}/>{done?'Completed · undo':'Mark complete'}</button></div>{next&&<a class="next-chapter" href={link(next)}><span><small>UP NEXT</small><b>{next.title}</b></span><Icon name="arrow"/></a>}</>}
 </div></div></>
}
function Search({onClose}){const [q,setQ]=useState(''),[index,setIndex]=useState([]),[loadError,setLoadError]=useState(false);const ref=useRef();const prev=useRef(document.activeElement);
 useEffect(()=>{ref.current?.focus();const c=new AbortController();fetch('./search-index.json',{signal:c.signal}).then(r=>{if(!r.ok)throw Error();return r.json()}).then(setIndex).catch(e=>{if(e.name!=='AbortError')setLoadError(true)});const handler=e=>{if(e.key==='Escape')onClose();if(e.key==='Tab'){const f=[...document.querySelectorAll('.search-dialog button,.search-dialog input,.search-dialog a')];const first=f[0],last=f.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus()}}};addEventListener('keydown',handler);const overflow=document.body.style.overflow;document.body.style.overflow='hidden';return()=>{c.abort();removeEventListener('keydown',handler);document.body.style.overflow=overflow;prev.current?.focus()}},[]);
 const query=q.trim().toLowerCase();const terms=query.split(/\s+/);const results=query?chapters.map(t=>{const title=(t.title+' '+t.summary).toLowerCase();const full=index.find(x=>x.id===t.id)?.text.toLowerCase()||'';return {t,score:terms.every(x=>title.includes(x))?3:terms.every(x=>(title+' '+full).includes(x))?1:0,full}}).filter(x=>x.score).sort((a,b)=>b.score-a.score).slice(0,30):chapters.filter(t=>['ai-map','gpu','linear-algebra','transformer-architecture','rag-memory-systems'].includes(t.id)).map(t=>({t}));
 return <div class="search-backdrop" onClick={onClose}><section class="search-dialog" role="dialog" aria-modal="true" aria-label="Search the library" onClick={e=>e.stopPropagation()}><div class="search-input-wrap"><Icon name="search"/><input ref={ref} value={q} onInput={e=>setQ(e.target.value)} placeholder="Search topics, concepts, or equations…" aria-label="Search all chapters"/><button class="icon-button" onClick={onClose} aria-label="Close search"><Icon name="close"/></button></div><div class="search-info" aria-live="polite">{query?`${results.length}${results.length===30?'+':''} matching chapters`:'POPULAR STARTING POINTS'}{loadError&&' · searching titles and summaries only'}</div><div class="search-results">{results.map(({t,score,full})=>{const at=full?.indexOf(terms[0]);return <a href={link(t)} onClick={onClose}><span class="search-result-icon"><Icon name={domains.find(x=>x.id===t.group)?.icon}/></span><div><small>{domains.find(x=>x.id===t.group)?.name}</small><h3>{t.title}</h3><p>{score===1&&at>=0?'…'+full.slice(Math.max(0,at-60),at+140)+'…':t.summary}</p></div><Icon name="arrow" size={17}/></a>})}{!results.length&&<div class="empty-state"><h3>No matching chapters</h3><p>Try a broader term such as memory, training, or probability.</p></div>}</div><footer><span>Searches chapter text as well as titles</span><span>ESC to close</span></footer></section></div>
}
function Sources(){const unique=new Map();chapters.forEach(t=>t.sources.forEach(([name,url])=>{if(!unique.has(url))unique.set(url,{name,topics:[]});unique.get(url).topics.push(t)}));return <><PageHead eyebrow="THE EVIDENCE LEDGER" title="Know what supports a claim." text="Named papers, textbooks, and practical documentation used while assembling the library. This index keeps you inside Axiom; it is a map of provenance, not a collection of outbound links."/><div class="source-policy"><Icon name="book" size={24}/><div><h3>Evidence should be inspectable, dated, and proportional to the claim.</h3><p>The library combines newly written foundations, the existing Frontier reference, and the Revolution fieldbook. Fast-moving product or policy claims belong to their stated date and conditions.</p></div></div><div class="source-list">{[...unique.values()].map((s,i)=><div><span>{String(i+1).padStart(2,'0')}</span><section><b>{s.name==='Primary research paper'?byId[s.topics[0].id].title+' — original research':s.name}</b><small>Referenced in {s.topics.length} chapter{s.topics.length===1?'':'s'}</small><div>{s.topics.map(t=><a href={link(t)}>{t.title}</a>)}</div></section></div>)}</div><Footer/></>}
function Labs(){const [tab,setTab]=useState('gradient');return <><PageHead eyebrow="THE INTERACTIVE WORKBENCH" title="Build your intuition." text="Change the inputs, inspect the result, and connect the behavior to the theory. All four experiments run locally in your browser."/><div class="filter-bar lab-tabs" role="tablist" aria-label="Experiments">{[['gradient','Gradient descent'],['softmax','Softmax & temperature'],['memory','Model memory'],['attention','Attention weights']].map(([id,name])=><button role="tab" aria-selected={tab===id} class={tab===id?'active':''} onClick={()=>setTab(id)}>{name}</button>)}</div><div role="tabpanel">{tab==='gradient'?<Gradient/>:tab==='softmax'?<Softmax/>:tab==='memory'?<Memory/>:<Attention/>}</div><Footer/></>}
function Range({label,value,onInput,min,max,step=1,suffix=''}){return <label class="lab-control"><span>{label}<output>{value}{suffix}</output></span><input type="range" value={value} min={min} max={max} step={step} onInput={e=>onInput(+e.target.value)}/></label>}
function Gradient(){const [lr,setLr]=useState(.15),[start,setStart]=useState(7),[steps,setSteps]=useState(0);let values=[start];for(let i=0;i<steps;i++)values.push(values.at(-1)-lr*2*(values.at(-1)-2));const w=values.at(-1),loss=(w-2)**2;const x=v=>60+(v+2)/10*620,y=v=>310-Math.min(50,(v-2)**2)/50*260;const points=Array.from({length:101},(_,i)=>{const v=-2+i*.1;return `${x(v)},${y(v)}`}).join(' ');return <div class="lab-panel"><div class="lab-main"><div class="eyebrow">EXPERIMENT 01 / OPTIMIZATION</div><h2>Find the bottom of the curve.</h2><p>Minimize L(w) = (w − 2)². Each step follows w ← w − η · 2(w − 2).</p><svg viewBox="0 0 740 370" role="img" aria-label="Quadratic loss curve and the gradient descent trajectory"><path d="M60 35v275h640" fill="none" stroke="#bec7d5"/><polyline points={points} fill="none" stroke="#2465e6" stroke-width="3"/>{[0,1,2,3,4,5,6,7].map(v=><text x={x(v)} y="337" text-anchor="middle" class="chart-label">{v}</text>)}<text x="375" y="363" text-anchor="middle" class="chart-label">Parameter w</text><polyline points={values.filter(v=>v>=-2&&v<=8).map(v=>`${x(v)},${y(v)}`).join(' ')} fill="none" stroke="#cc6336" stroke-width="2" stroke-dasharray="5 4"/>{values.filter(v=>v>=-2&&v<=8).map((v,i)=><circle cx={x(v)} cy={y(v)} r={i===values.length-1?7:4} fill={i===values.length-1?'#ce592d':'#c9d7f6'} stroke="white" stroke-width="2"/>)}</svg><div class="lab-explanation"><strong>{lr>1?'The updates diverge.':lr===1?'The updates oscillate.':lr>.5?'The updates cross the minimum.':'The updates approach the minimum.'}</strong><p>{lr>=1?'For this quadratic, a rate of 1 is the stability boundary. Beyond it, each update moves farther away.':'The same objective can behave very differently with a different step size. This toy curve is convex; real neural-network losses are more complicated.'}</p></div></div><aside class="lab-settings"><h3>Experiment controls</h3><Range label="Learning rate η" value={lr} min={.01} max={1.2} step={.01} onInput={v=>{setLr(v);setSteps(0)}}/><Range label="Starting weight" value={start} min={-1} max={7} step={.5} onInput={v=>{setStart(v);setSteps(0)}}/><button class="primary-link" disabled={steps>=15} onClick={()=>setSteps(steps+1)}>Take one step <Icon name="arrow" size={16}/></button><button class="secondary-button" onClick={()=>setSteps(0)}>Reset experiment</button><div class="lab-readouts"><div><span>Step</span><b>{steps} / 15</b></div><div><span>Weight</span><b>{w.toFixed(4)}</b></div><div><span>Loss</span><b>{loss.toFixed(4)}</b></div></div><a href="#/read/optimization">Read about optimization ↗</a></aside></div>}
function Softmax(){const [temp,setTemp]=useState(1),[logit,setLogit]=useState(2);const vals=[logit,1,.2,-.5];const mx=Math.max(...vals);const es=vals.map(x=>Math.exp((x-mx)/temp)),sum=es.reduce((a,b)=>a+b,0),ps=es.map(x=>x/sum);return <div class="lab-panel"><div class="lab-main"><div class="eyebrow">EXPERIMENT 02 / PROBABILITY</div><h2>Turn scores into probabilities.</h2><p>softmax(zᵢ / T) = exp(zᵢ / T) / Σⱼ exp(zⱼ / T). Temperature changes the sharpness of this distribution.</p><div class="prob-bars">{ps.map((p,i)=><div><span>Token {String.fromCharCode(65+i)}</span><div><i style={{width:p*100+'%'}}/></div><b>{(p*100).toFixed(1)}%</b></div>)}</div><div class="lab-explanation"><strong>A sharper distribution is not a more accurate answer.</strong><p>Lower temperature concentrates probability on the highest-scoring option. It does not add evidence or repair incorrect scores. This demo visualizes probabilities; it does not sample tokens.</p></div></div><aside class="lab-settings"><h3>Experiment controls</h3><Range label="Temperature T" value={temp} min={.1} max={3} step={.1} onInput={setTemp}/><Range label="Token A logit" value={logit} min={-2} max={5} step={.1} onInput={setLogit}/><div class="lab-readouts"><div><span>Sum of probabilities</span><b>{ps.reduce((a,b)=>a+b,0).toFixed(4)}</b></div><div><span>Entropy</span><b>{(-ps.reduce((s,p)=>s+p*Math.log2(p),0)).toFixed(3)} bits</b></div></div><a href="#/read/information-theory">Read about entropy ↗</a></aside></div>}
function Memory(){const [params,setParams]=useState(8),[bits,setBits]=useState(16),[seq,setSeq]=useState(8192),[batch,setBatch]=useState(1),[layers,setLayers]=useState(32),[heads,setHeads]=useState(8);const weights=params*1e9*bits/8/2**30,kv=2*batch*seq*layers*heads*128*2/2**30,total=weights+kv;return <div class="lab-panel"><div class="lab-main"><div class="eyebrow">EXPERIMENT 03 / CAPACITY PLANNING</div><h2>Will the model fit?</h2><p>Separate weights from the KV cache. This is an inference memory lower bound, with a 128-dimensional head and BF16 KV cache.</p><div class="memory-total"><b>{total.toFixed(2)}<small> GiB</small></b><span>Weights + KV cache</span></div><div class="memory-stack"><i style={{width:weights/total*100+'%'}}/><i style={{width:kv/total*100+'%'}}/></div><div class="memory-legend"><span><i/>Weights {weights.toFixed(2)} GiB</span><span><i/>KV cache {kv.toFixed(2)} GiB</span></div><div class="lab-explanation"><strong>Plan for more than this number.</strong><p>Activations, runtime, workspaces, allocator overhead, quantization scales, and temporary buffers are excluded. Parameter count does not determine architecture: layer and KV-head counts are independently adjustable. Grouped-query attention uses KV heads here, not query heads.</p><code>KV bytes = 2 × batch × tokens × layers × KV heads × head dimension × bytes</code></div></div><aside class="lab-settings"><h3>Model assumptions</h3><Range label="Parameters" value={params} min={1} max={120} onInput={setParams} suffix=" B"/><label class="lab-control"><span>Weight precision</span><select value={bits} onChange={e=>setBits(+e.target.value)}><option value="32">FP32 · 4 bytes</option><option value="16">BF16 / FP16 · 2 bytes</option><option value="8">INT8 / FP8 · 1 byte</option><option value="4">4-bit · 0.5 byte (ideal)</option></select></label><Range label="Context tokens" value={seq} min={1024} max={131072} step={1024} onInput={setSeq}/><Range label="Concurrent sequences" value={batch} min={1} max={32} onInput={setBatch}/><Range label="Layers" value={layers} min={8} max={128} step={8} onInput={setLayers}/><Range label="KV heads" value={heads} min={1} max={64} onInput={setHeads}/><a href="gpu.html#s18">Open the GPU memory chapter ↗</a></aside></div>}
function Attention(){const [row,setRow]=useState(3),[causal,setCausal]=useState(true);const tokens=['The','robot','moves','the','box'];const scores=[.3,1.4,.8,.2,1.8];const allowed=scores.map((s,i)=>causal&&i>row?0:Math.exp(s));const denom=allowed.reduce((a,b)=>a+b,0);return <div class="lab-panel"><div class="lab-main"><div class="eyebrow">EXPERIMENT 04 / ATTENTION</div><h2>Decide where to look.</h2><p>Select a query position. The causal mask blocks later positions before the row is normalized. Scores are illustrative and fixed to isolate the effect of masking.</p><div class="token-buttons">{tokens.map((t,i)=><button class={row===i?'active':''} onClick={()=>setRow(i)}>{t}<small>position {i}</small></button>)}</div><div class="attention-cells">{allowed.map((s,i)=><div style={{background:s?`rgba(25,94,228,${.08+.65*s/denom})`:'#f1f3f6'}}><span>{tokens[i]}</span><b>{s?(s/denom*100).toFixed(1)+'%':'MASKED'}</b></div>)}</div><div class="lab-explanation"><strong>Mask first. Normalize second.</strong><p>Masked scores behave like negative infinity inside softmax. Allowed weights sum to one and determine a weighted sum of value vectors. In a real model, learned query and key vectors generate different scores for every row.</p></div></div><aside class="lab-settings"><h3>Experiment controls</h3><label class="check-control"><input type="checkbox" checked={causal} onChange={e=>setCausal(e.target.checked)}/>Causal attention</label><div class="lab-readouts"><div><span>Query position</span><b>{row}</b></div><div><span>Visible positions</span><b>{causal?row+1:5} / 5</b></div></div><a href="#/read/transformer-architecture">Read about attention ↗</a></aside></div>}
function Empty({title,text}){return <div class="empty-state"><Icon name="book" size={35}/><h2>{title}</h2><p>{text}</p><a class="primary-link" href="#/library">Explore the library <Icon name="arrow" size={16}/></a></div>}
function Footer(){return <footer class="site-footer"><a class="footer-brand" href="#/">A<span>•</span>xiom</a><p>Understand the machine. Question the system.</p><a href="#/sources">Evidence index ↗</a></footer>}
render(<App/>,document.getElementById('app'));
